Fix/lint issues
FyshOS/fynedesk pull request #241
Opened 2023-01-09 20:35 UTC by rafaelsousa

### Description:

Fixes #(issue)

### Checklist:

- [x] Tests included.
- [x] Lint and formatter run with no errors.
- [x] Tests all pass.

#### Where applicable:

- [ ] Public APIs match existing style.
- [ ] Any breaking changes have a deprecation path or have been discussed.
- [ ] Updated the vendor folder (using `go mod vendor`).

2023-01-09 22:03 UTC, andydotxyz requested changes
We can't use os.ReadFile yet as we support back to Go 1.14 and it was not present then.

2023-01-10 07:51 UTC, Jacalz commented
It looks like there still are a few places where ioutil has been removed. That will need to be added back.

2023-01-10 20:24 UTC, rafaelsousa commented
> We can't use os.ReadFile yet as we support back to Go 1.14 and it was not present then.

The os.Readfile references were reverted.

2023-01-10 22:49 UTC, andydotxyz reviewed
Looking great thanks - just checking about the TODO

2023-01-10 22:49 UTC, andydotxyz commented on modules/systray/main.go
> +	// TODO: See the need of returning this error
Is this TODO supposed to be there? Not sure I understand the comment

2023-01-14 20:32 UTC, andydotxyz approved these changes

2023-01-14 20:32 UTC, merged